version: '3.9'

services:

  ngrok:
    image: wernight/ngrok:latest
    env_file: ./config/.env

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf

  webhook:
    build: ./webhook
    restart: always
    env_file: ./config/.env

  backend:
    build: ./src
    restart: always

  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./database/data:/var/lib/postgresql/data
    env_file: ./config/.env
