version: '3.9'

services:

#    ngrok:
#        image: wernight/ngrok:latest
#        environment:
#            - NGROK_AUTH=${NGROK_AUTH}
#            - NGROK_PORT=${NGROK_PORT}

    nginx:
        image: nginx:latest        
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "5678:80"
        depends_on:
#            - webhook
            - frontend
            - backend
            - db

#    webhook:
#        build: ./webhook
#        environment:
#            - WEBHOOK_PASSWORD=${WEBHOOK_PASSWORD}
#            - WEBHOOK_PAGE_TOKEN=${WEBHOOK_PAGE_TOKEN}

    frontend:
        build: 
            context: ./frontend
            args:
                - FRONTEND_DOMAIN=${FRONTEND_DOMAIN}

    backend:
        build: ./src/
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

    db:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
