version: '3.9'

services:

    ngrok:
        image: wernight/ngrok:latest
        env_file: ./config/.env

    nginx:
        image: nginx:latest        
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "5678:80"

    webhook:
        build: ./webhook
        env_file: ./config/.env

    frontend:
        build: ./frontend
        env_file: ./config/.env

    backend:
        build: ./src/
        env_file: ./config/.env

    db:
        image: postgres:latest
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data:z
        env_file: ./config/.env
